### PR TITLE
export native Promise firstly

### PR DESCRIPTION
**Pull request by ik0r**

### CODE REVIEW

**Comment by Zolmeister** [comment]
thanks

**Comment by Zolmeister** [comment]
So I reverted this because it broke tests (tests never hit the lib), but also because I reconsidered and think it is a mistake to expose the global through the lib. The correct usage is to polyfill the global itself.

**Comment by ik0r** [comment]
> The correct usage is to polyfill the global itself.

@Zolmeister what's the meaning?

**Comment by Zolmeister** [comment]
``` js
window.Promise = window.Promise || require('promiz')
```

**Pull request merged**
